### ISSUE TITLE
これよかったなっていう物まねを別途保存しておく

### ISSUE THREAD

**Issue by rockyh0825** [Kitsuya0828/Inpersonation-App#19]

**Comment by rockyh0825** [comment]
ギャラリーみたいな感じで残しておけたらいいな
（せっかくだから何かデータベース使った実装しておきたいという思いもある笑）

**Comment by kitsuyaazuma** [comment]
いいと思う🙆‍♀️
シングルモードのところに追加実装してもええで

**Comment by rockyh0825** [comment]
ひとまず、デフォルトのランキングを反映させるところと、実際にシングルで遊んでランクインするかまでは実装したよ。
document管理したら一瞬でした、(人''▽｀)ありがとう☆
明日はページ作って表示するところの実装からやるよ～

**Comment by kitsuyaazuma** [comment]
┏○)) ｱｻﾞ━━━━━━━━ｽ！
